### ISSUE TITLE
Can you add the platforms which I mentioned too? It will be very useful!

### ISSUE THREAD

**Issue by vasanthgk02** [karanarjunjr/cp-calendar#1]
Your project is awezome. But adding hackerrank,GFG,  TopCoder, AtCoder too makes it more awezome!

**Comment by karanarjunjr** [comment]
Thanks for the complement. If I'm not wrong GFG, TopCoder and AtCoder are already present in the filters. I haven't added Hackerrank because they don't conduct contests regularly.
