### ISSUE TITLE
Extension not working!!

### ISSUE THREAD

**Issue by jha-om** [karanarjunjr/cp-calendar#10]
I have tried to re-install it 2 times but it freezes on the compiling part.

Have also tried on Brave (as it's on the same engine as Chrome) but again the same thing.

I guess Clist API is not responding to your software.
![Screenshot 2024-05-14 205915](https://github.com/karanarjunjr/cp-calendar/assets/94907651/65fa3b5a-9005-4b32-a432-7a8b9ef042cd)

**Comment by SANJAY072000** [comment]
Yes it stopped working suddenly.

**Comment by UditUchiha** [comment]
Yeah, it just freezes on the compiling part.

**Comment by tachyon29** [comment]
https://bright-fly-undershirt.cyclic.app/clist.by:443 The server on which app is hosted is down. Can fix for yourself by replacing it directly with https://clist.by:443 in the custom.js file apiURL2. Can then go to chrome extensions , enable developer mode and upload your local cloned folder with the changes, will fix it.
