### ISSUE TITLE
API issue 

### ISSUE THREAD

**Issue by Telomelonia** [karanarjunjr/cp-calendar#7]
The extension is not showing any output... might be due to a failing API connection 
![image](https://github.com/karanarjunjr/cp-calendar/assets/88445101/d2e729d0-d123-4a0c-a28f-b97d12db501c)

**Comment by ShivanshGupta02** [comment]
yeah same for me

**Comment by prathmesh0203** [comment]
is this resolved?

**Comment by suryapratap9** [comment]
Someone, please fix this.

**Comment by jha-om** [comment]
Hey, @karanarjunjr please fix the issue mentioned by @Telomelonia. It's been over a month about the issue. First I thought there is an issue from my chrome web store side, therefore I have reinstalled the extension again, but the issue remains same.

**Comment by karanarjunjr** [comment]
Glad you guys found my work helpful! I have fixed the issue. Thanks for letting me know :)
